# Generated by Django 5.2.8 on 2025-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the TODO item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the TODO is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the TODO was created')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
